### ISSUE TITLE
BBAA.txt for only 1 trio

### ISSUE THREAD

**Issue by Marlappp** [millanek/Dsuite#35]
Hi, 
I have been trying to use Dsuite but I have ran into some issues.
So in my vcf file I have 63 indivs belonging to 3 species/populations and 1 outgroup but when I run Dtrios I only get result for 1 trio and not all possible combinations...
Do you have any ideas why that might be?

Thanks so much for your help.

**Comment by millanek** [comment]
Hi - that makes perfect sense... three species and one outgroup = one trio

What else did you expect and why?
Milan

**Comment by biopitch** [comment]
Hi Dr. Malinsky, 

I would like to jump onto this issue because I think I have a similar question to the poster. 

I have 3 species and an outgroup which makes one trio but I only get one permutation of the trio. e.g. species1 = P1, species2 = P2 and species 3 = P3. I am actually interested in species3 = P1, species2 = P2 and species1 = P3. 

Reading your paper, it states "[Dtrios] orders each trio assuming that the correct tree is the one where the BBAA pattern is more common than the discordant ABBA and BABA pattern". From my understanding of this sentence, the species being categorises into P1, P2 and P3 depends on the BBAA numbers and I would not be able to other permutation of this trio. Is this correct?
