### ISSUE TITLE
Some problems about Dsuit

### ISSUE THREAD

**Issue by sy-snake** [millanek/Dsuite#5]
Dear Milan Malinsky,

Some problems occured when I uesd Dsuit.

First, the parameter -f of Dsuite Dtrios. After the run of Dsuite Dtrios whith -f, the f4, f_d, and f_dM statistics did not appear in the output files. And there is no Z-score in output files.

Second, the output of 'Dsuite Dinvestigate' of 0.2 version is different with the output of 0.1 version. The f_d of version 0.2 is much bigger then D, but f_d is lesser then D in the output of version 0.1. And the windowStart of version 0.1 is scientific counting, this may be corrected in version 0.2. But the output files of version 0.2 has lesser lines then version 0.1. The output of 'Dsuite Dinvestigate' of the two version are completely different. Which one should I believe?

Best regards,
Yang Song

**Comment by sy-snake** [comment]
Here's an example,
D=0.372182
f_G=0.469002    200134/426722
f_d=0.912107    453964/497709
f_dM=0.633232   453964/716900
At the genome-wide scale, the D is 0.37, but f_d is as high as 0.91. This result is the output of 'Dsuite Dinvestigate'.

**Comment by millanek** [comment]
Hi Yang Song

Thanks for pointing out these things. 
1) You are right, the Dsuite Dtrios -f parameter isn't working yet... I am working on it and it should be finished soon. Maybe one week. I am going to let you know here.

2) I was improving how 'Dsuite Dinvestigate' works. There were a few changes, finally I think it is much improved! Actually, I should start a proper change log because it looks like many people are using Dsuite. 

To answer you main question: I suggest that you use and trust the latest version which I pushed to gitHub yesterday: v0.2 r12. 

Also, you are right in your observation that f_d was too high: I am afraid that the f_G, f_d, and f_dM statistics between v0.1 r4 and v0.2 r11 (that's November 6th until November 29th 2019) are overestimated. 

I add here some technical explanation about the changes in Dinvestigate:
I was changing how the sliding windows are calculated. This is why the number of lines in the output files is different. Now only sites which are ABBA and/or BABA informative are included in calculating the size of the window. This means that the windows are averaging over the same number of informative sites, and therefore more likely to have equal amount of information coming into them. You will find that the signal in v0.2 r12 has much less variance than previously and that signals of introgression are much clearer. Because of this change, you might want to use smaller values for the -w parameter than in v0.1 r1 to v0.1 r3 to get similar physical intervals. 

Unfortunately, when changing the window size calculations, I forgot that some sites which are not ABBA and/or BABA informative still contribute to the denominators of f_G, f_d, and f_dM. Therefore, the denominators of these statistics were underestimated in v0.2 r4 to v0.2 r11, as you noticed in terms of these estimates being too high. Sorry about that. I believe it should work very well now.

**Comment by sy-snake** [comment]
Hi Malinsky,
Thanks for changing code so quickly.
And&nbsp;I am not clear about the calculation process of p value, could you explain to me how to calculate the p value?
Yang Song



---Original---

**Comment by millanek** [comment]
Translating the Z-scores to p-values is straightforward: the Zscores have a standard [https://en.wikipedia.org/wiki/Normal_distribution](normal distribution) so I use the cumulative distribution function to get the p-value.

**Comment by silvewheat** [comment]
Hi Malinsky,

I use Dsuite Dinvestigate (Version: 0.4 r34) with "-w 100,50", it seems the value of fD still higher than D. Is it worked as expected?

e.g.:
D = 0.16344
f_d = 0.552369	
f_dM = 0.290023
d_f = 0.084759

Best,
Yudong
